# Generated by Django 3.0.6 on 2020-05-16 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('u_tube', '0002_auto_20200516_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 14, 19, 24, 71042, tzinfo=utc)),
        ),
    ]
