# Generated by Django 3.0.6 on 2020-05-19 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('u_tube', '0003_video_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(default='', upload_to='video_thumb/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 12, 32, 53, 105218, tzinfo=utc)),
        ),
    ]
