# Generated by Django 3.0.6 on 2020-05-19 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('u_tube', '0004_auto_20200519_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 14, 26, 50, 41129, tzinfo=utc)),
        ),
    ]
